Add : SearchBar 기능 구현
wecode-bootcamp-korea/10-Weplash-backend pull request #12
Opened 2020-08-10 02:53 UTC by soojung601

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
SearchBar 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
SearchBar 추천 검색어 용 hashtag 이름 리턴

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [X] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-08-10 02:55 UTC, evergreen-david requested changes

2020-08-10 02:55 UTC, evergreen-david commented on photo/views.py
> +        return JsonResponse({"data" : result}, status=200)
데이터가 많은경우 성능 문제가 발생할수 있으므로 default LIMIT 설정해주는게 좋을것같습니다.

2020-08-10 02:59 UTC, soojung601 commented on photo/views.py
> +        return JsonResponse({"data" : result}, status=200)
* 대화 완료 * 😄

2020-08-11 11:31 UTC, evergreen-david approved these changes

2020-08-11 11:31 UTC, merged