백그라운드 메인 추가
wecode-bootcamp-korea/10-Weplash-backend pull request #16
Opened 2020-08-12 05:42 UTC by dhkim12310

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-08-12 07:57 UTC, evergreen-david requested changes

2020-08-12 07:57 UTC, evergreen-david commented on photo/urls.py
> +    path('/collection-main', CollectionMainView.as_view()),
main 은 엔드포인트 URL에  포함안해도 될것 같지만, main 의 의미를 꼭 주고싶으면 main-collection 추천 드립니다.

```suggestion
    path('/main-collection, CollectionMainView.as_view()),
```

2020-08-12 11:21 UTC, dhkim12310 commented on photo/urls.py
> +    path('/collection-main', CollectionMainView.as_view()),
수정 하였습니다

2020-08-13 04:14 UTC, evergreen-david requested changes

2020-08-13 04:14 UTC, evergreen-david commented on photo/views.py
> +            user = User.objects.filter(photo__photocollection__collection = Collection.objects.get(user=User.objects.get(user_name='weplash'),name='Nature')).distinct().annotate(count=Count('photo__i
Collection, User 간의 관계가 있지않나요 ? 쿼리 같이 할 수 있는지 검토해보고 쿼리 정리 부탁 드립니다.!

2020-08-13 06:39 UTC, dhkim12310 commented on photo/views.py
> +            user = User.objects.filter(photo__photocollection__collection = Collection.objects.get(user=User.objects.get(user_name='weplash'),name='Nature')).distinct().annotate(count=Count('photo__i
collection변수 는 카테고리의 정보를 담기 위해 만들었고 유저 weplash는 진짜 유저가 아니라 카테고리를 만들때사용하는 공식 계정으로 사용하기 위해 만들었습니다 
그리고 user변수 는 카테고리안의 유저가 올린사진의 갯수를 세기위해 만들었습니다
두 정보를 합쳐보려 노력했으나 상관관계를 찾는데 어려움이 있어 다른 방법을 생각해내지 못했습니다

2020-08-13 08:01 UTC, evergreen-david requested changes

2020-08-13 08:01 UTC, evergreen-david commented on photo/tests.py
> +>>>>>>> c7f4650... 콜렉션 메인 정보추가 및 백그라운드뷰 수정
정리 부탁 드립니다.

2020-08-13 08:01 UTC, evergreen-david commented on photo/views.py
> +            user = User.objects.filter(photo__photocollection__collection = Collection.objects.get(user=User.objects.get(user_name='weplash'),name='Nature')).distinct().annotate(count=Count('photo__i
네 알겠습니다. 해당 get 메소드에대한 유닛테스트는 다른 PR에 있나요 ?

2020-08-13 15:02 UTC, lordmyshepherd approved these changes

2020-08-13 15:02 UTC, merged