Feature/signup
wecode-bootcamp-korea/10-Weplash-backend pull request #5
Opened 2020-08-06 04:23 UTC by minho-lee0716

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
회원가입, 로그인 엔드포인트, 구현
		 
## 수정 사항들 자세한 내용

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [V] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [V] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [V] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [V] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [V] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-08-06 07:38 UTC, soheon-lee commented on account/views.py
> +from django.shortcuts       import render
사용하지 않는 코드입니다 삭제해주세요

2020-08-06 07:38 UTC, soheon-lee commented on account/views.py
> +    if len(password) > 5:
비밀번호는 다섯글자만 넘으면 되나요?

2020-08-06 07:38 UTC, soheon-lee commented on account/views.py
> +            elif (vu and vp) == True:
`vu and vp`와 같이 값 자체가 boolean일 경우 비교 연산자를 사용하지 않고 바로 사용하는 것이 보다 파이썬스러운 흐름입니다.
```suggestion
            elif (vu and vp):
```

2020-08-06 07:38 UTC, soheon-lee commented on account/views.py
> +                return JsonResponse({'message':'VALIDATION_ERROR'}, status=400)
`else`가 없어도 위에서 `return`된다면 바로 도달할 수 있는 코드이므로 `else`를 제거해도 좋을 것 같습니다.

2020-08-06 07:38 UTC, soheon-lee commented on account/views.py
> +            if (validation_password(password) and User.objects.filter(email=email).exists()) == True:
값 자체가 boolean일 경우 비교 연산자를 사용하지 않고 바로 사용하는 것이 보다 파이썬스러운 흐름입니다.

2020-08-06 07:38 UTC, soheon-lee commented on config/urls.py
> +    path('', include('account.urls'))
```suggestion
    path('account', include('account.urls'))
```
바로 account.urls로 연결하는 것보다는 url에 앱 이름을 명시해주는 것이 좋습니다.

2020-08-06 08:25 UTC, minho-lee0716 commented on config/urls.py
> +    path('', include('account.urls'))
넹

2020-08-06 08:26 UTC, minho-lee0716 commented on account/views.py
> +from django.shortcuts       import render
넵

2020-08-06 08:28 UTC, minho-lee0716 commented on account/views.py
> +    if len(password) > 5:
넵 원래 사이트에도 비밀번호는 6자 이상이면 됩니다!

TMI = user_name은 유니크이며 '영문 대소문자 + 언더바 까지' 입니다.

2020-08-06 08:31 UTC, minho-lee0716 commented on account/views.py
> +            elif (vu and vp) == True:
제가 착각을 했네요. vu와 vp가 모두 True여야 회원가입을 시키는거라,
(vu and vp and True)로 바꾸겠습니다~

2020-08-06 08:33 UTC, minho-lee0716 commented on account/views.py
> +                return JsonResponse({'message':'VALIDATION_ERROR'}, status=400)
else 지우고 return 문장 indent 한 탭 줄여줬습니다~

2020-08-06 08:35 UTC, minho-lee0716 commented on account/views.py
> +            if (validation_password(password) and User.objects.filter(email=email).exists()) == True:
이것도 위와같이 혼돈했습니다. 다 같이 True일 때 만, 가입을 시키는거라 and True로 변경하겠습니다

2020-08-06 09:01 UTC, minho-lee0716 commented
나머지는 저녁 먹고와서 수정하겠습니다~

2020-08-07 02:13 UTC, evergreen-david requested changes

2020-08-07 02:13 UTC, evergreen-david commented on account/tests.py
> +    URL = 'https://images.unsplash.com/placeholder-avatars/extra-large.jpg?dpr=1&auto=format&fit=crop&w=150&h=150&q=60&crop=faces&bg=fff'
테스트용 URL은 실제 url을 사용하는것보다  'url'정도로해서 테스트하셔도 괜찮을것 같습니다.

2020-08-07 02:19 UTC, minho-lee0716 commented on account/tests.py
> +    URL = 'https://images.unsplash.com/placeholder-avatars/extra-large.jpg?dpr=1&auto=format&fit=crop&w=150&h=150&q=60&crop=faces&bg=fff'
바로 수정했습니다!

2020-08-07 02:33 UTC, soheon-lee commented on account/views.py
> +    if len(password) > 5:
하드코딩으로 오해받을 가능성이 있습니다. 정규식으로 한 번 시도해주세요 :)

2020-08-07 02:33 UTC, soheon-lee commented on account/views.py
> +        return False
len(user_name)이 0인 경우도 사실 위의 정규식과 일치 하지 않는 경우에 해당하지 않을까요? 혹시 굳이 명시하신 이유가 있나요?

2020-08-07 02:33 UTC, soheon-lee commented on account/views.py
> +            elif (vu and vp and True):
🙂  여기서 뒤에 `True`를 붙이신 이유가 무엇일까요?

2020-08-07 02:33 UTC, soheon-lee commented on account/views.py
> +    URL = 'https://images.unsplash.com/placeholder-avatars/extra-large.jpg?dpr=1&auto=format&fit=crop&w=150&h=150&q=60&crop=faces&bg=fff'
프로필 사진의 기본 URL이라면 변수 이름을 보다 명확히 해주세요

2020-08-07 02:33 UTC, soheon-lee commented on auth.py
> +                user_id      = data['user_id']
`=` 전에 간격 너무 넓습니다. 조정해주세요

2020-08-07 02:34 UTC, soheon-lee commented on account/views.py
> +                return JsonResponse({'message':'THIS USER NAME ALREADY EXISTS'}, status=400)
상위 `if`문에서 `return`되지 않는다면 바로 도달 할 수 있는 코드이므로 `elif`보다는 `if`문을 독립적으로 사용하시는 것을 추천드립니다.

2020-08-07 03:02 UTC, minho-lee0716 commented on account/views.py
> +    URL = 'https://images.unsplash.com/placeholder-avatars/extra-large.jpg?dpr=1&auto=format&fit=crop&w=150&h=150&q=60&crop=faces&bg=fff'
넵~

2020-08-07 04:28 UTC, minho-lee0716 commented on account/views.py
> +            elif (vu and vp and True):
제가 큰 착각을 했습니다 ㅠㅠ and가 모두 True여야 True를 리턴하는데 저는 조건이 두개 같으면, 예를 들어 둘 다 False여도 True가 반환될줄알았습니다. 아래 SignInView에도 수정 해줬습니다~

2020-08-07 04:31 UTC, minho-lee0716 commented on auth.py
> +                user_id      = data['user_id']
넵~

2020-08-07 04:32 UTC, minho-lee0716 commented on account/views.py
> +                return JsonResponse({'message':'THIS USER NAME ALREADY EXISTS'}, status=400)
와우 그렇군요 수정했습니다

2020-08-07 05:18 UTC, minho-lee0716 commented on account/views.py
> +        return False
user_name은 꼭 줘야하는데 안주면 안돼서 0을 준 것이고, 제가 못찾는건지 모르겠는데 아무리 찾아봐도 공백말고 아예 안들어오면 찾아주는(?) 그런게 없는것 같아서 줬습니다. 저렇게 조건을 안주고 함수를 실행 할 때, 인자에 ('') 이렇게 주어도 True로 나오더라구요.

일단 수정 안하고 올릴게요. 피드백 부탁드립니다🙏

2020-08-07 09:54 UTC, merged