URL쿼리스트링, 뷰, 유닛테스트 추가
wecode-bootcamp-korea/10-Weplash-backend pull request #8
Opened 2020-08-07 13:53 UTC by dongsagi90

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-08-11 11:02 UTC, evergreen-david requested changes

2020-08-11 11:02 UTC, evergreen-david commented on photo/views.py
> +class BackgraundView(View):
```suggestion
class BackgroundView(View):
```

2020-08-11 11:45 UTC, soheon-lee commented on photo/tests.py
> +            password = '123456',
코드 간격 모두 맞춰주세요

2020-08-11 11:45 UTC, soheon-lee commented on photo/tests.py
> +            background_color_id = bc.id
코드 간격 모두 맞춰주세요

2020-08-11 11:45 UTC, soheon-lee commented on photo/tests.py
> +            collection_id = collection.id
코드 간격 모두 맞춰주세요

2020-08-11 11:45 UTC, soheon-lee commented on photo/tests.py
> +            password = '123456',
코드 간격 모두 맞춰주세요

2020-08-11 11:45 UTC, soheon-lee commented on photo/tests.py
> +            background_color_id = bc.id
코드 간격 모두 맞춰주세요

2020-08-11 11:45 UTC, soheon-lee commented on photo/tests.py
> +            password = '123456',
코드 간격 모두 맞춰주세요

2020-08-11 11:45 UTC, soheon-lee commented on photo/tests.py
> +            background_color_id = bc.id
코드 간격 모두 맞춰주세요

2020-08-11 11:45 UTC, soheon-lee commented on photo/views.py
> +            user_category = request.GET.get('user_category',None)
코드 간격 모두 맞춰주세요

2020-08-11 11:45 UTC, soheon-lee commented on photo/views.py
> +                "height" : photo.height
코드 간격 모두 맞춰주세요

2020-08-11 11:45 UTC, soheon-lee commented on photo/views.py
> +            user = request.GET.get('user',None)
`user`정보를 `body`에서 꺼내오시는건가요? 로그인을 한 상태라면, token을 활용해보세요 :)

2020-08-11 11:47 UTC, soheon-lee commented on photo/views.py
> +                    ), collection__name = user_category),query.AND)
어떤 빈 쿼리를 먼저 선언하신 후, 특정한 조건이 충족될 때마다 조건을 확장시키고자 하시는거죠?
if 에 해당할 때마다 `and` 조건으로 묶는 것이 좋은 생각인 것 같습니다 :)

query.add(  , query.AND) 도 좋지만 보다 자주 사용되는 파이썬 로직을 사용해보시는 것을 추천드립니다. 흔히 특정 변수에다 어떤 것을 추가할 때 `i += 1` 과 같은 문법을 사용하죠? 활용하실 수 있을 것 같습니다.

또한, query를 한 번에 만드시고, `filter(query)` 도 진짜 좋은 방법인 것 같아요! :) django 로직을 조금 수정해주시면 더 좋을 것 같아요. 먼저, `like__user`이나 `collection__user`을 사용하신 이유가 collection 클래스에 user 객체가 속성으로 있기 때문이죠? 그렇다면 user_name도 사실은 user의 속성이기 때문에 `__`로 접근하실 수 있습니다 한 번 활용해보세요. 가져올 때마다 `get(  )`를 사용하시게 되면 때마다 데이터 베이스에 쿼리가 날아가게 됩니다 (database hit 라고 부릅니다.) db hit을 최소한으로 줄이도록 리팩토링 해나가야 합니다.

2020-08-11 13:01 UTC, dhkim12310 commented on photo/views.py
> +            user = request.GET.get('user',None)
로그인한 상태는 다음 버전에 준비되어있습니다

2020-08-11 13:04 UTC, dhkim12310 commented on photo/views.py
> +            user = request.GET.get('user',None)
로그인 한 상태는 다음버전에 준비되어 있습니다

2020-08-11 15:29 UTC, dhkim12310 commented on photo/views.py
> +            user = request.GET.get('user',None)
아직 로그인 기능을 구현하지 않고 메인을 보여줄 생각으로 만들었습니다

2020-08-12 01:43 UTC, evergreen-david requested changes

2020-08-12 01:43 UTC, evergreen-david commented on photo/views.py
> +                # ).exists()
주석 정리 부탁 드립니다.

2020-08-12 05:16 UTC, evergreen-david commented
@dhkim12310 rebase 부탁 드리겠습니다.

2020-08-12 05:18 UTC, closed without merging