파일 업로드 API
wecode-bootcamp-korea/10-Weplash-backend pull request #9
Opened 2020-08-08 06:08 UTC by soojung601

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
- 파일 업로드 기능 구현
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)
- 파일 업로드 시 view는 s3에 업로드 후 success return
- celery를 이용해 비동기로 DB에 저장 및 이미지 처리(related tags, background_color)
## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 
- unittest 구현 중입니다!
## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [X] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-08-11 04:45 UTC, soheon-lee commented on photo/tasks.py
> +                )
response.json()['result']['tags']라는 키가 존재하지 않을 경우엔 프론트엔드에게 어떻게 알려줄 수 있을까요?

2020-08-11 04:45 UTC, soheon-lee commented on photo/tasks.py
> +
위와 비슷한 경우입니다.
['result']['colors']등의 키가 없을 수도 있는데, 처리해주셔야 할 것 같아요 :)

2020-08-11 04:45 UTC, soheon-lee commented on photo/views.py
> +                "user_like"          : photo.like_set.filter(user=User.objects.filter(id=user_id).first(), status=True).exists(),
이미 user_id를 알고 있는 경우라면, user를 기준으로 필터링할 때 User 객체를 쿼리하지 않고도 바로 사용하실 수 있습니다.

2020-08-11 04:45 UTC, soheon-lee commented on photo/views.py
> +                        user = User.objects.filter(id=user_id).first()
이미 user_id를 알고 있는 경우라면, user를 기준으로 필터링할 때 User 객체를 쿼리하지 않고도 바로 사용하실 수 있습니다.

2020-08-11 04:45 UTC, soheon-lee commented on photo/views.py
> +                    aws_secret_access_key = AWS_S3['secret_access_key']
간격 맞춰주세요

2020-08-11 04:45 UTC, soheon-lee commented on photo/views.py
> +                im = Image.open(urlopen(S3_URL+url_id))
변수명 `im`이 뜻하는 의미가 무엇일까요?

2020-08-11 04:45 UTC, soheon-lee commented on photo/views.py
> +                    user        = User.objects.get(id=user_id),
이미 user_id를 알고 있는 경우라면, User 객체를 쿼리하지 않고도 바로 사용하실 수 있습니다.

2020-08-11 06:14 UTC, soojung601 commented on photo/tasks.py
> +                )
KeyError 인 경우 photo.status 를 False로 바꾸게 처리했고, 나중에 프론트와 협의해서 유저페이지 들어갔을 때 status가 False인 photo가 있으면 위에 알림창 띄울 수 있게 얘기해볼게요!

2020-08-11 06:14 UTC, soojung601 commented on photo/views.py
> +                im = Image.open(urlopen(S3_URL+url_id))
image 로 바꿨습니다!

2020-08-11 11:22 UTC, evergreen-david requested changes

2020-08-11 11:22 UTC, evergreen-david commented on photo/tasks.py
> +        photo.save()
except 문안에서 실제 수행하는 코드를 실행하게끔하면안됩니다. 말그대로 예외 상황이기 때문에 적절한 에러만 리턴해야하고 해당로직은 try문안에서 분기해서 처리해주시겠어요 ?

2020-08-11 11:23 UTC, evergreen-david requested changes

2020-08-11 11:23 UTC, evergreen-david commented on photo/views.py
> +                return JsonResponse({'message' : 'SUCCESS'}, status=200)
```suggestion
                return HttpResponse(status=200)
```

2020-08-11 11:40 UTC, evergreen-david requested changes

2020-08-11 11:40 UTC, evergreen-david commented on photo/tasks.py
> +        color = response.json()['result']['colors']['background_colors'][0]['html_code']
if "result" in response.json():
    color = response.json()['result']['colors']['background_colors'][0]['html_code']
else:
    photo.status = False
    photo.save()

2020-08-12 02:29 UTC, evergreen-david approved these changes

2020-08-12 02:30 UTC, merged